include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # avoid_print: false
    # prefer_single_quotes: true

analyzer:
  plugins:
    - dart_style

dart_style:
  line-length: 100
  page-width: 100
  format-single-line-constructors: false
