// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6XWdcVnFaFDDsHDAJNzYi_p7VHszg6Dk',
    appId: '1:1091231397342:web:5aa20d119467727779594f',
    messagingSenderId: '1091231397342',
    projectId: 'nextalk-7005d',
    authDomain: 'nextalk-7005d.firebaseapp.com',
    storageBucket: 'nextalk-7005d.firebasestorage.app',
    measurementId: 'G-JVR4E2V436',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe8puGSDFPzfkfYZ3F2KuiRHam0LBpqL0',
    appId: '1:1091231397342:android:a04803dcd39e1d7a79594f',
    messagingSenderId: '1091231397342',
    projectId: 'nextalk-7005d',
    storageBucket: 'nextalk-7005d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ91IbzO5JzTvfnn4dIOJzaWWWkPBGOEs',
    appId: '1:1091231397342:ios:52bb78af500a8fc779594f',
    messagingSenderId: '1091231397342',
    projectId: 'nextalk-7005d',
    storageBucket: 'nextalk-7005d.firebasestorage.app',
    iosBundleId: 'com.example.nextalk',
  );
}
